TASK1:
  name: MultiRC
  loss: CrossEntropyLoss
  process: normal
  task_id: 1
  dataroot: datasets/MultiRC
  max_seq_length: 23
  batch_size: 128
  eval_batch_size: 1024
  train_split: trainval
  val_split: minval
  lr: 0.00004
  num_epoch: 20
TASK2:
  name: CoLA
  loss: CrossEntropyLoss
  process: normal
  task_id: 2
  dataroot: datasets/CoLA
  max_seq_length: 26
  batch_size: 128
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20
TASK3:
  name: SocialIQA
  loss: CrossEntropyLoss
  process: normal
  task_id: 3
  dataroot: datasets/SocialIQA
  max_seq_length: 16
  batch_size: 64
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20